# # Etapa de construção
# FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
# WORKDIR /app

# # Copiar o código para o contêiner
# COPY . ./

# # Restaurar dependências
# RUN dotnet restore

# # Publicar a aplicação em modo Release
# RUN dotnet publish -c Release -o /publish

# # Etapa de runtime
# FROM mcr.microsoft.com/dotnet/aspnet:8.0
# WORKDIR /app

# # Copiar os arquivos publicados
# COPY --from=build /publish .

# # Expor a porta usada pela aplicação
# EXPOSE 80

# # Comando para iniciar a aplicação
# ENTRYPOINT ["dotnet", "IClinicBot.Application.API.dll"]


# Usar a imagem base do .NET SDK para build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app

# Copiar arquivos do projeto e restaurar dependências
COPY *.csproj ./
RUN dotnet restore

# Copiar o restante do código e compilar a aplicação
COPY . ./
RUN dotnet publish -c Release -o out

# Usar a imagem base do runtime para rodar a aplicação
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build-env /app/out .

# Expor a porta padrão
EXPOSE 80

# Comando para rodar a aplicação
ENTRYPOINT ["dotnet", "IClinicBot.Application.API.dll"]
